"""add avatar, garment, outfit images 

Revision ID: fed1ba4a428c
Revises: 24f1eb53b023
Create Date: 2026-10-08 02:13:40.603619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed1ba4a428c'
down_revision: Union[str, Sequence[str], None] = '24f1eb53b023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_key')
    )
    op.create_index(op.f('ix_user_avatars_id'), 'user_avatars', ['id'], unique=False)
    op.create_index(op.f('ix_user_avatars_user_id'), 'user_avatars', ['user_id'], unique=True)
    op.create_table('garment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_key')
    )
    op.create_index(op.f('ix_garment_images_garment_id'), 'garment_images', ['garment_id'], unique=False)
    op.create_index(op.f('ix_garment_images_id'), 'garment_images', ['id'], unique=False)
    op.create_table('outfit_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_key')
    )
    op.create_index(op.f('ix_outfit_images_id'), 'outfit_images', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_images_outfit_id'), 'outfit_images', ['outfit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_images_outfit_id'), table_name='outfit_images')
    op.drop_index(op.f('ix_outfit_images_id'), table_name='outfit_images')
    op.drop_table('outfit_images')
    op.drop_index(op.f('ix_garment_images_id'), table_name='garment_images')
    op.drop_index(op.f('ix_garment_images_garment_id'), table_name='garment_images')
    op.drop_table('garment_images')
    op.drop_index(op.f('ix_user_avatars_user_id'), table_name='user_avatars')
    op.drop_index(op.f('ix_user_avatars_id'), table_name='user_avatars')
    op.drop_table('user_avatars')
    # ### end Alembic commands ###
